// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nzvhkyrvxidvhfuejsiy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im56dmhreXJ2eGlkdmhmdWVqc2l5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyMzExMDcsImV4cCI6MjA2OTgwNzEwN30.qXTK2Y1MOULapj4QH4pimvhyjB8zCfh8sQArfEpx6Tc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});